version: 0.2

phases:
  install: 
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...    
  build:
    commands:
      - pip3 install
      - pysimplegui install
artifacts:
  type: zip
  paths:
    - '*'
